-- ================================================================
-- setup.sql — Supabase Full Schema Setup
-- Jalankan di Supabase SQL Editor (Dashboard → SQL Editor)
-- Idempotent: aman dijalankan berulang
-- ================================================================

-- ================================================================
-- 1. TABLES
-- ================================================================

-- 1a. packages (lookup)
CREATE TABLE IF NOT EXISTS public.packages (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL UNIQUE,
  is_active   bool DEFAULT true,
  sort_order  int DEFAULT 0
);

-- 1b. clients (tenants)
CREATE TABLE IF NOT EXISTS public.clients (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nama_acara  text NOT NULL,
  token       text NOT NULL UNIQUE,
  pin_scanner text,
  base_url    text,
  paket       text DEFAULT 'lite',
  package_id  uuid REFERENCES public.packages(id) ON DELETE SET NULL,
  max_tamu    int DEFAULT 100,
  max_wa      int DEFAULT 50,
  wa_mode     text DEFAULT 'admin',
  wa_nomor    text,
  wa_api_key  text,
  wa_media_url    text,
  wa_media_nama   text,
  wa_terkirim     int DEFAULT 0,
  tanggal_acara   date,
  reminder_rsvp_aktif     bool DEFAULT false,
  reminder_rsvp_jadwal    date,
  reminder_rsvp_template  text,
  reminder_h3             bool DEFAULT false,
  reminder_h1             bool DEFAULT false,
  reminder_template_h3    text,
  reminder_template_h1    text,
  reminder_ucapan_aktif       bool DEFAULT false,
  reminder_ucapan_jadwal      date,
  reminder_ucapan_template    text,
  reminder_ucapan_target      text DEFAULT 'hadir',
  pesan_template  text,
  created_at      timestamptz DEFAULT now()
);

-- 1c. themes (lookup)
CREATE TABLE IF NOT EXISTS public.themes (
  id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name        text NOT NULL UNIQUE,
  theme_code  text,
  is_active   bool DEFAULT true,
  sort_order  int DEFAULT 0
);

-- 1d. invitations
CREATE TABLE IF NOT EXISTS public.invitations (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  slug        text NOT NULL UNIQUE,
  theme_id    int REFERENCES public.themes(id) ON DELETE SET NULL,
  package_id  uuid REFERENCES public.packages(id) ON DELETE SET NULL,
  is_published bool DEFAULT false,
  is_active   bool DEFAULT true,
  expired_at  timestamptz,
  section_styles jsonb DEFAULT NULL,

  bride_name      text,
  bride_nickname  text,
  bride_father    text,
  bride_mother    text,
  bride_instagram text,
  bride_photo_url text,

  groom_name      text,
  groom_nickname  text,
  groom_father    text,
  groom_mother    text,
  groom_instagram text,
  groom_photo_url text,

  quote       text,
  hashtag     text,
  music_url   text,
  view_count  int DEFAULT 0,
  created_at  timestamptz DEFAULT now()
);

-- 1e. events
CREATE TABLE IF NOT EXISTS public.events (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invitation_id   uuid NOT NULL REFERENCES public.invitations(id) ON DELETE CASCADE,
  event_name      text,
  event_date      date,
  start_time      time,
  end_time        time,
  location_name   text,
  address         text,
  maps_url        text,
  livestream_url  text,
  sort_order      int DEFAULT 0,
  custom_style    jsonb DEFAULT NULL,
  created_at      timestamptz DEFAULT now()
);

-- 1f. bank_accounts
CREATE TABLE IF NOT EXISTS public.bank_accounts (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invitation_id   uuid NOT NULL REFERENCES public.invitations(id) ON DELETE CASCADE,
  type            text DEFAULT 'bank',
  bank_name       text,
  account_number  text,
  account_name    text,
  sort_order      int DEFAULT 0,
  created_at      timestamptz DEFAULT now()
);

-- 1g. love_stories
CREATE TABLE IF NOT EXISTS public.love_stories (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invitation_id   uuid NOT NULL REFERENCES public.invitations(id) ON DELETE CASCADE,
  event_date      date,
  title           text,
  description     text,
  photo_url       text,
  sort_order      int DEFAULT 0,
  created_at      timestamptz DEFAULT now()
);

-- 1h. galleries
CREATE TABLE IF NOT EXISTS public.galleries (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invitation_id   uuid NOT NULL REFERENCES public.invitations(id) ON DELETE CASCADE,
  file_url        text,
  caption         text,
  is_cover        bool DEFAULT false,
  sort_order      int DEFAULT 0,
  created_at      timestamptz DEFAULT now()
);

-- 1i. tamu_undangan (guest list)
CREATE TABLE IF NOT EXISTS public.tamu_undangan (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id       uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  invitation_id   uuid REFERENCES public.invitations(id) ON DELETE SET NULL,
  nama            text,
  telpon          text,
  status_kirim    bool DEFAULT false,
  status_buka     bool DEFAULT false,
  waktu_buka      timestamptz,
  created_at      timestamptz DEFAULT now()
);

-- 1j. rsvp_tamu
CREATE TABLE IF NOT EXISTS public.rsvp_tamu (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id       uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  tamu_id         uuid REFERENCES public.tamu_undangan(id) ON DELETE SET NULL,
  pos_id          text,
  nama            text,
  telpon          text,
  kehadiran       text,
  pesan           text,
  qr_token        text,
  status_hadir    bool DEFAULT false,
  waktu_hadir     timestamptz,
  created_at      timestamptz DEFAULT now()
);

-- 1k. komentar (comments / wishes)
CREATE TABLE IF NOT EXISTS public.komentar (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  tamu_id     uuid REFERENCES public.tamu_undangan(id) ON DELETE SET NULL,
  nama        text,
  isi         text,
  created_at  timestamptz DEFAULT now()
);

-- 1l. wa_log (whatsapp send history)
CREATE TABLE IF NOT EXISTS public.wa_log (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  tamu_id     uuid REFERENCES public.tamu_undangan(id) ON DELETE SET NULL,
  nomor       text,
  nama        text,
  pesan       text,
  status      text,
  tipe        text,
  sent_at     timestamptz DEFAULT now()
);

-- 1m. reminder_log
CREATE TABLE IF NOT EXISTS public.reminder_log (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  tamu_id     uuid REFERENCES public.tamu_undangan(id) ON DELETE SET NULL,
  tipe        text,
  status      text,
  sent_at     timestamptz DEFAULT now()
);

-- 1n. kirim_jadwal (scheduled bulk send)
CREATE TABLE IF NOT EXISTS public.kirim_jadwal (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id     uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  tamu_ids      text[] DEFAULT '{}',
  waktu_kirim   timestamptz,
  total_tamu    int,
  status        text DEFAULT 'terjadwal',
  terkirim      int DEFAULT 0,
  created_at    timestamptz DEFAULT now()
);

-- 1o. admin_settings (global config)
CREATE TABLE IF NOT EXISTS public.admin_settings (
  id    text PRIMARY KEY,
  value text
);


-- ================================================================
-- 2. INDEXES
-- ================================================================

-- rsvp_tamu
CREATE INDEX IF NOT EXISTS idx_rsvp_tamu_client_id   ON public.rsvp_tamu (client_id);
CREATE INDEX IF NOT EXISTS idx_rsvp_tamu_qr_token     ON public.rsvp_tamu (qr_token) WHERE qr_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_rsvp_tamu_tamu_id      ON public.rsvp_tamu (tamu_id);

-- komentar
CREATE INDEX IF NOT EXISTS idx_komentar_client_id ON public.komentar (client_id);
CREATE INDEX IF NOT EXISTS idx_komentar_created_at ON public.komentar (created_at DESC);

-- tamu_undangan
CREATE INDEX IF NOT EXISTS idx_tamu_undangan_client_id ON public.tamu_undangan (client_id);

-- wa_log
CREATE INDEX IF NOT EXISTS idx_wa_log_client_id ON public.wa_log (client_id);
CREATE INDEX IF NOT EXISTS idx_wa_log_sent_at   ON public.wa_log (sent_at DESC);

-- reminder_log
CREATE INDEX IF NOT EXISTS idx_reminder_log_client_id ON public.reminder_log (client_id);

-- kirim_jadwal
CREATE INDEX IF NOT EXISTS idx_kirim_jadwal_client_id  ON public.kirim_jadwal (client_id);
CREATE INDEX IF NOT EXISTS idx_kirim_jadwal_waktu      ON public.kirim_jadwal (waktu_kirim) WHERE status IN ('terjadwal', 'sebagian');

-- invitations
CREATE INDEX IF NOT EXISTS idx_invitations_client_id ON public.invitations (client_id);
CREATE INDEX IF NOT EXISTS idx_invitations_slug       ON public.invitations (slug);

-- events
CREATE INDEX IF NOT EXISTS idx_events_invitation_id ON public.events (invitation_id);

-- bank_accounts
CREATE INDEX IF NOT EXISTS idx_bank_accounts_invitation_id ON public.bank_accounts (invitation_id);

-- love_stories
CREATE INDEX IF NOT EXISTS idx_love_stories_invitation_id ON public.love_stories (invitation_id);

-- galleries
CREATE INDEX IF NOT EXISTS idx_galleries_invitation_id ON public.galleries (invitation_id);


-- ================================================================
-- 3. RPC FUNCTIONS
-- ================================================================

CREATE OR REPLACE FUNCTION public.increment_view_count(inv_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.invitations
  SET view_count = COALESCE(view_count, 0) + 1
  WHERE id = inv_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.increment_wa_terkirim(p_client_id uuid, p_jumlah int DEFAULT 1)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.clients
  SET wa_terkirim = COALESCE(wa_terkirim, 0) + p_jumlah
  WHERE id = p_client_id;
END;
$$;


-- ================================================================
-- 4. ROW LEVEL SECURITY
-- ================================================================

-- Note: App uses anon key with query-level filtering (?client_id=eq.xxx).
-- Policies allow all operations; access control is handled via the
-- client_id filter in every request. For stricter security, replace
-- USING (true) with USING (client_id = auth.uid()::uuid) after
-- implementing Supabase Auth for end-users.

-- clients
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "clients_all" ON public.clients;
CREATE POLICY "clients_all" ON public.clients USING (true);

-- invitations
ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "invitations_all" ON public.invitations;
CREATE POLICY "invitations_all" ON public.invitations USING (true);

-- events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "events_all" ON public.events;
CREATE POLICY "events_all" ON public.events USING (true);

-- bank_accounts
ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bank_accounts_all" ON public.bank_accounts;
CREATE POLICY "bank_accounts_all" ON public.bank_accounts USING (true);

-- love_stories
ALTER TABLE public.love_stories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "love_stories_all" ON public.love_stories;
CREATE POLICY "love_stories_all" ON public.love_stories USING (true);

-- galleries
ALTER TABLE public.galleries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "galleries_all" ON public.galleries;
CREATE POLICY "galleries_all" ON public.galleries USING (true);

-- tamu_undangan
ALTER TABLE public.tamu_undangan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tamu_undangan_all" ON public.tamu_undangan;
CREATE POLICY "tamu_undangan_all" ON public.tamu_undangan USING (true);

-- rsvp_tamu
ALTER TABLE public.rsvp_tamu ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "rsvp_tamu_all" ON public.rsvp_tamu;
CREATE POLICY "rsvp_tamu_all" ON public.rsvp_tamu USING (true);

-- komentar
ALTER TABLE public.komentar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "komentar_all" ON public.komentar;
CREATE POLICY "komentar_all" ON public.komentar USING (true);

-- wa_log
ALTER TABLE public.wa_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "wa_log_all" ON public.wa_log;
CREATE POLICY "wa_log_all" ON public.wa_log USING (true);

-- reminder_log
ALTER TABLE public.reminder_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "reminder_log_all" ON public.reminder_log;
CREATE POLICY "reminder_log_all" ON public.reminder_log USING (true);

-- kirim_jadwal
ALTER TABLE public.kirim_jadwal ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "kirim_jadwal_all" ON public.kirim_jadwal;
CREATE POLICY "kirim_jadwal_all" ON public.kirim_jadwal USING (true);

-- admin_settings
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "admin_settings_all" ON public.admin_settings;
CREATE POLICY "admin_settings_all" ON public.admin_settings USING (true);

-- themes
ALTER TABLE public.themes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "themes_all" ON public.themes;
CREATE POLICY "themes_all" ON public.themes USING (true);

-- packages
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "packages_all" ON public.packages;
CREATE POLICY "packages_all" ON public.packages USING (true);


-- ================================================================
-- 5. STORAGE BUCKETS
-- ================================================================

INSERT INTO storage.buckets (id, name, public, avif_autodetection)
VALUES ('profile-photos', 'profile-photos', true, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public, avif_autodetection)
VALUES ('gallery-photos', 'gallery-photos', true, false)
ON CONFLICT (id) DO NOTHING;

-- Allow public access to storage buckets
DROP POLICY IF EXISTS "storage_public_read" ON storage.objects;
CREATE POLICY "storage_public_read" ON storage.objects
  FOR SELECT USING (bucket_id IN ('profile-photos', 'gallery-photos'));

DROP POLICY IF EXISTS "storage_public_insert" ON storage.objects;
CREATE POLICY "storage_public_insert" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id IN ('profile-photos', 'gallery-photos'));

DROP POLICY IF EXISTS "storage_public_update" ON storage.objects;
CREATE POLICY "storage_public_update" ON storage.objects
  FOR UPDATE USING (bucket_id IN ('profile-photos', 'gallery-photos'));

DROP POLICY IF EXISTS "storage_public_delete" ON storage.objects;
CREATE POLICY "storage_public_delete" ON storage.objects
  FOR DELETE USING (bucket_id IN ('profile-photos', 'gallery-photos'));


-- ================================================================
-- 6. SEED DATA
-- ================================================================

-- Themes
INSERT INTO public.themes (name, theme_code, is_active, sort_order) VALUES
  ('sakina',  'sakina',  true, 1),
  ('arafa',   'arafa',   true, 2),
  ('sahara',  'sahara',  true, 3),
  ('medina',  'medina',  true, 4)
ON CONFLICT (name) DO NOTHING;

-- Packages
INSERT INTO public.packages (name, is_active, sort_order) VALUES
  ('lite',    true, 1),
  ('pro',     true, 2),
  ('premium', true, 3)
ON CONFLICT (name) DO NOTHING;


-- ================================================================
-- 7. REALTIME (manual via Dashboard)
-- ================================================================
-- Enable Realtime untuk table berikut via Supabase Dashboard:
-- Database → Replication → Enable Realtime on:
--   tamu_undangan, rsvp_tamu, komentar, wa_log, reminder_log, clients
--
-- SQL alternatif (jika Supabase support publication management):
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.tamu_undangan;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.rsvp_tamu;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.komentar;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.wa_log;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.reminder_log;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.clients;


-- ================================================================
-- 8. VERIFIKASI
-- ================================================================
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
-- ORDER BY table_name;
--
-- SELECT p.proname FROM pg_proc p
-- JOIN pg_namespace n ON p.pronamespace = n.oid
-- WHERE n.nspname = 'public' AND p.proname IN ('increment_view_count', 'increment_wa_terkirim');
