#!/usr/bin/env node
/**
 * build.js — Generate env.js from Cloudflare Pages environment variables
 * Run as build command in Cloudflare Pages dashboard
 */
const fs = require('fs');
const path = require('path');

const envVars = {
  SUPABASE_URL:  process.env.SUPABASE_URL  || '',
  SUPABASE_KEY:  process.env.SUPABASE_KEY  || '',
  PUBLIC_DOMAIN: process.env.PUBLIC_DOMAIN || '',
  FONNTE_API:    process.env.FONNTE_API    || '',
  DEFAULT_THEME: process.env.DEFAULT_THEME || 'sakina'
};

const content = `// Auto-generated by build.js — DO NOT EDIT
window.__ENV = {
  SUPABASE_URL:  '${envVars.SUPABASE_URL}',
  SUPABASE_KEY:  '${envVars.SUPABASE_KEY}',
  PUBLIC_DOMAIN: '${envVars.PUBLIC_DOMAIN}',
  FONNTE_API:    '${envVars.FONNTE_API}',
  DEFAULT_THEME: '${envVars.DEFAULT_THEME}'
}
`;

fs.writeFileSync(path.join(__dirname, 'env.js'), content);
console.log('env.js generated from environment variables');
